version: '3'
networks: 
  smart_classroom: 
    driver: bridge

services: 
  auth-frontend:
    restart: always
    container_name: auth-frontend
    build: ./auth-frontend
    ports:
      - 3000:80
    networks:
      - smart_classroom

  backend:
    restart: always
    container_name: backend
    build: .
    ports:
      - 8081:8081
    networks:
      - smart_classroom

  postgres:
    restart: always
    container_name: postgres
    build: ./Database 
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes: 
      - progresDB_data:/var/lib/postgresql/data
      - ./Database/postgres.conf:/database/config/postgres.conf
    networks:
      - smart_classroom

volumes:
  progresDB_data: