version: '3'
networks: 
  smart_classroom: 
    driver: bridge

services: 
  auth-frontend:
    restart: always
    container_name: auth-frontend
    build: ./auth-frontend
    ports:
      - 3000:80
    networks:
      - smart_classroom
  backend:
    restart: always
    container_name: backend
    build:
      context: .
      dockerfile: server/http-api/Dockerfile
    ports:
      - 8081:8081
    networks:
      - smart_classroom
  websocket:
    restart: always
    container_name: websocket
    build:
      context: .
      dockerfile: server/ws/Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - smart_classroom
  postgres:
    restart: always
    container_name: postgres
    build: ./Database 
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes: 
      - progresDB_data:/var/lib/postgresql/data
      - ./Database/postgres.conf:/database/config/postgres.conf
    networks:
      - smart_classroom
  notification:
    restart: always
    container_name: notificationwk
    build:
      context: .
      dockerfile: notificationwk/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - smart_classroom
  rabbitmq:
    restart: always
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - smart_classroom
    volumes:
    - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

volumes:
  progresDB_data: